insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (1, 'Toyota', '2023-06-28', 'Camry');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (2, 'Cadillac', '2023-12-28', 'Seville');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (3, 'Mercedes-Benz', '2023-04-17', 'CLS-Class');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (4, 'Honda', '2023-05-27', 'Civic');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (5, 'Harley-Davidson', '2023-12-30', 'Fat Boy');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (6, 'Yamaha', '2023-05-21', 'YZF-R1');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (7, 'Honda', '2023-06-13', 'CBR600RR');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (8, 'Kawasaki', '2023-10-14', 'Ninja ZX-10R');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (9, 'Specialized', '2023-06-25', 'Stumpjumper');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (10, 'Trek', '2023-08-04', 'Domane');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (11, 'Cannondale', '2023-11-30', 'Synapse');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (12, 'Giant', '2023-08-02', 'Anthem');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (13, 'Caterpillar', '2024-01-04', '745C');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (14, 'Volvo', '2023-09-12', 'A60H');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (15, 'Komatsu', '2023-04-20', 'HM400-5');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (16, 'Hitachi', '2023-05-20', 'EH5000AC-3');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (17, 'John Deere', '2023-05-05', '8R 410');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (18, 'New Holland', '2023-12-05', 'T7.270');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (19, 'Massey Ferguson', '2023-07-01', '7726');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (20, 'Case IH Magnum', '2023-09-09', '340');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (21, 'Volvo', '2023-05-02', 'FMX');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (22, 'Scania', '2023-04-12', 'P-series');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (23, 'Mercedes-Benz', '2023-09-09', 'Actros');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (24, 'Kenworth', '2023-09-17', 'T880');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (25, 'Volvo', '2023-04-30', 'FH16');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (26, 'MAN', '2023-07-11', 'TGX');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (27, 'DAF', '2024-01-17', 'XF');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (28, 'Iveco', '2023-09-08', 'S-Way');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (29, 'Ford', '2023-05-23', 'F-350');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (30, 'Chevrolet', '2023-10-06', 'C3500');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (31, 'Acura', '2023-06-07', 'NSX');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (32, 'Saturn', '2023-09-12', 'L-Series');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (33, 'Lotus', '2023-09-29', 'Esprit');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (34, 'Isuzu', '2023-08-03', 'Rodeo');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (35, 'GMC', '2024-03-22', 'Envoy');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (36, 'Aptera', '2023-11-29', '2e');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (37, 'Land Rover', '2023-11-22', 'Discovery');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (38, 'Volkswagen', '2023-10-17', 'Passat');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (39, 'Mazda', '2023-10-07', '929');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (40, 'Cadillac', '2024-03-07', 'XLR-V');