insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (1, 'Toyota', '2023-06-28', 'Camry');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (2, 'Cadillac', '2023-12-28', 'Seville');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (3, 'Mercedes-Benz', '2023-04-17', 'CLS-Class');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (4, 'Honda', '2023-05-27', 'Civic');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (5, 'Harley-Davidson', '2023-12-30', 'Fat Boy');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (6, 'Yamaha', '2023-05-21', 'YZF-R1');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (7, 'Honda', '2023-06-13', 'CBR600RR');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (8, 'Toyota', '2023-10-14', 'Avalon');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (9, 'Ford', '2023-06-25', 'Explorer Sport Trac');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (10, 'Mercury', '2023-08-04', 'Cougar');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (11, 'Chevrolet', '2023-11-30', 'Suburban 1500');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (12, 'Mercedes-Benz', '2023-08-02', 'CL-Class');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (13, 'Ford', '2024-01-04', 'E-Series');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (14, 'Mercury', '2023-09-12', 'Tracer');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (15, 'Isuzu', '2023-04-20', 'Trooper');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (16, 'Kia', '2023-05-20', 'Sportage');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (17, 'Bentley', '2023-05-05', 'Continental GT');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (18, 'BMW', '2023-12-05', '7 Series');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (19, 'Chrysler', '2023-07-01', '300M');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (20, 'Acura', '2023-09-09', 'Integra');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (21, 'Saab', '2023-04-12', '9-5');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (22, 'Chevrolet', '2023-05-02', 'Suburban 1500');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (23, 'Suzuki', '2023-09-09', 'XL-7');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (24, 'Mazda', '2023-09-17', 'Protege');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (25, 'Maserati', '2023-04-30', 'Quattroporte');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (26, 'Mitsubishi', '2023-07-11', 'Galant');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (27, 'Mercury', '2024-01-17', 'Villager');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (28, 'Toyota', '2023-09-08', 'Tundra');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (29, 'Volkswagen', '2023-05-23', 'Passat');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (30, 'Suzuki', '2023-10-06', 'Equator');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (31, 'Acura', '2023-06-07', 'NSX');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (32, 'Saturn', '2023-09-12', 'L-Series');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (33, 'Lotus', '2023-09-29', 'Esprit');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (34, 'Isuzu', '2023-08-03', 'Rodeo');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (35, 'GMC', '2024-03-22', 'Envoy');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (36, 'Aptera', '2023-11-29', '2e');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (37, 'Land Rover', '2023-11-22', 'Discovery');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (38, 'Volkswagen', '2023-10-17', 'Passat');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (39, 'Mazda', '2023-10-07', '929');
insert into descripcion_vehiculo (id_descripcion, marca, fecha_lanzamiento, modelo) values (40, 'Cadillac', '2024-03-07', 'XLR-V');
